#!/usr/bin/env bash
# Script that configures a new Ubuntu machine with the following requirements:

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/error_404.html > /dev/null

sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/def

sudo service nginx restart
